### ISSUE TITLE
Uncaught TypeError: Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by ghost** [olmokramer/atom-css-specificity#1]
[Enter steps to reproduce below:]
1. Simply starting Atom produced this error.

**Atom Version**: 1.0.11
**System**: Ubuntu 15.04
**Thrown From**: [css-specificity](https://github.com/olmokramer/atom-css-specificity) package, v0.1.3
### Stack Trace

Uncaught TypeError: Cannot read property 'add' of undefined

```
At /home/tec/.atom/packages/css-specificity/lib/css-specificity-status.js:63

TypeError: Cannot read property 'add' of undefined
    at /home/tec/.atom/packages/css-specificity/lib/css-specificity-status.js:63:25
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:276:9)
    at css-specificity-status.createdCallback (/home/tec/.atom/packages/css-specificity/lib/css-specificity-status.js:37:22)
    at cssSpecificityStatus (/home/tec/.atom/packages/css-specificity/lib/css-specificity-status.js:146:19)
    at Object.consumeStatusBar (/home/tec/.atom/packages/css-specificity/lib/main.js:36:11)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at process._tickCallback (node.js:357:13)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "audioBeep": false
  }
}
```
### Installed Packages

``` coffee
# User
atom-autocomplete-php, v0.10.1
atom-image-resize, v0.3.0
atom-minify, v0.4.1
autoclose-html, v0.19.0
autocomplete-php, v0.3.7
browser-plus, v0.0.34
css-specificity, v0.1.3
drop-base64-encoding, v0.2.0
less-autocompile, v1.0.0
linter, v1.5.2
linter-csslint, v1.0.5
linter-gcc, v0.3.8
linter-htmlhint, v0.1.1
linter-jshint, v1.2.0
linter-less, v2.1.0
linter-php, v1.0.3
linter-sass-lint, v0.1.4
linter-scss-lint, v2.0.0
minimap, v4.13.3
php-cs-fixer, v2.4.0
sass-autocompile, v0.9.0

# Dev
No dev packages
```

**Comment by ghost** [comment]
Looking at this and [the other error](https://github.com/olmokramer/atom-css-specificity/issues/2), this seems to be related. Trying to narrow things down, it seems to be caused by the fact there was a tab named "untitled" (containing an empty, unsaved document). Upon launching, this tab was recreated – causing atom-css to fail, closing that tab and making sure that there is no such "untitled", unsaved document open in Atom upon launch seems to solve the issue all together.

**Comment by olmokramer** [comment]
Thanks for taking the time to look further into this issue! Still, this shouldn't happen... I'll reopen this issue until it is resolved. We can leave the other one closed, and continue discussion here.

**Comment by ghost** [comment]
No problem. Just didn’t want to "pollute" the issues area too much after I could limit it to an _"only happens when having an untitled, unsaved document tab open"_ instead of an _"oh my God we are all going to die"_ kind of thing.

Anyway… meanwhile – after diving into half a truckload of atom, atom-css and other sourcecode – my gut feeling tells me it might just have been the result of a "caching glitch" or something alike. This would practically mean it’s it’s more probable that the reported error actually originated in something atom itself messed up, while dear, little atom-css is actually innocent and working as it should.

This is somewhat underlined by the fact that  – after cleaning atom-related caching data – I am meanwhile unable to reproduce this formerly reproduceable error. Yes, I’m not kidding you. I could reproduce those two errors all day, even accross OS reboots. But after manually whiping some of atoms own cache stuff (stuff it stores on close and reads at start) I seem to be unable to hit those errors, no matter what I try. As said: my gut feeling tells me it was more of an atom caching glitch.

From coder to coder: this is one of those situations where I really hate not having hooked up some IO logging. If I would have, we would now probably be a bit smarter as to what file(s) may have been causing these error messages, and why.

In case it helps: what I know for sure is that  `undefined` in each error message clearly pointed to an "untitled" tab with no content (created but not saved by me, yet remembered and recreated by atom on quit/launch). To make atom-css a bit more robust in alike as well as in other situations, it may be a good idea to implement some simple object-checks at the start/top of functions. Meaning: based on those errors it seems to me as if it makes sense to let atom-css functions verify if – whatever they are trying to access (file, tabbed window, etc) – actually is accessible and not `undefined`as it obviously was in case of the reported errors. Might be me, but letting atom-css blindly run into darkness, trusting that atom and co didn’t mess things up somewhere along the road seems to be just a little bit “too trusty”. OTOH, what do I know? Since I bluntly forgot to kick in some independant IO logging while trying to hunt down that bug today, I’m having a bit of a trust issue with my own brain right now…  Whatever. Please feel invited to ping me whenever you think it makes sense.

`/* Time for my “I should’ve logged that IO” facepalm. */`

**Comment by Getron** [comment]
+1

**Comment by olmokramer** [comment]
I think I solved the issue. It seems it had to do with a CSS file being open on startup of Atom. I'll release a new version soon!

**Comment by olmokramer** [comment]
I just published the new version. Please let me know if you're still encountering this
